// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Toolkit from "@reduxjs/toolkit";

var initialState = {
  paintColour: "#000000",
  showGridLines: true
};

function reducers_setPaintColour(state, action) {
  state.paintColour = action.payload;
  
}

function reducers_toggleShowGridLines(state, action) {
  state.showGridLines = !state.showGridLines;
  
}

var reducers = {
  setPaintColour: reducers_setPaintColour,
  toggleShowGridLines: reducers_toggleShowGridLines
};

var settingsSlice = Toolkit.createSlice({
      name: "settings",
      initialState: initialState,
      reducers: reducers
    });

export {
  initialState ,
  reducers ,
  settingsSlice ,
  
}
/* settingsSlice Not a pure module */
