// Generated by ReScript, PLEASE EDIT WITH CARE


var initialState = {
  paintColour: "#000000",
  showGridLines: true
};

function reducer(state, action) {
  if (action) {
    return {
            paintColour: action._0,
            showGridLines: state.showGridLines
          };
  } else {
    return {
            paintColour: state.paintColour,
            showGridLines: !state.showGridLines
          };
  }
}

export {
  initialState ,
  reducer ,
  
}
/* No side effect */
