// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GridSlice$RescriptReactIntro from "../../store/GridSlice.bs.js";

function Controls(Props) {
  
}

var make = Controls;

export {
  make ,
  
}
/* GridSlice-RescriptReactIntro Not a pure module */
