// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Grid$RescriptReactIntro from "./grid/Grid.bs.js";
import * as Redux$RescriptReactIntro from "../store/Redux.bs.js";
import * as Controls$RescriptReactIntro from "./controls/Controls.bs.js";

function app(param) {
  return CssJs.style([
              CssJs.display("flex"),
              CssJs.position("absolute"),
              CssJs.top(CssJs.px(0)),
              CssJs.left(CssJs.px(0)),
              CssJs.height({
                    NAME: "percent",
                    VAL: 100.0
                  }),
              CssJs.width({
                    NAME: "percent",
                    VAL: 100.0
                  })
            ]);
}

var Styles = {
  app: app
};

function App(Props) {
  var dispatch = Curry._1(Redux$RescriptReactIntro.Store.useDispatch, undefined);
  var updateGridDimension = function (param) {
    var appContainer = document.getElementById("appContainer");
    if (appContainer == null) {
      return ;
    }
    var height = appContainer.clientHeight;
    var width = appContainer.clientWidth;
    var targetHeight = height !== undefined && width !== undefined ? Math.min(height, width - 220 | 0) : 0;
    return Curry._1(dispatch, {
                TAG: /* SetDimension */3,
                _0: targetHeight
              });
  };
  React.useEffect(function () {
        updateGridDimension(undefined);
        window.addEventListener("resize", updateGridDimension);
        return (function (param) {
                  document.removeEventListener("resize", updateGridDimension);
                  
                });
      });
  return React.createElement("span", {
              className: app(undefined),
              id: "appContainer"
            }, React.createElement(Controls$RescriptReactIntro.make, {}), React.createElement(Grid$RescriptReactIntro.make, {}));
}

var make = App;

export {
  Styles ,
  make ,
  
}
/* CssJs Not a pure module */
