// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as App$RescriptReactIntro from "./components/App.bs.js";
import * as Redux$RescriptReactIntro from "./store/Redux.bs.js";

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(Redux$RescriptReactIntro.Store.Provider.make, {
            children: React.createElement(App$RescriptReactIntro.make, {}),
            store: Redux$RescriptReactIntro.store
          }), root);
}

export {
  
}
/* root Not a pure module */
